### PR TITLE
Finish bitfield test suite

### LINKED ISSUE #7: Finish writing the #[bitfield] test cases and explanations

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #7.

### CODE REVIEW

**Comment by dtolnay** [comment]
FYI @Robbepop

**Comment by Robbepop** [comment]
Are you going to add solutions to the workshop items to have a go-to when they are stuck or do you accept such solutions? They could for example live in another branch.

**Comment by dtolnay** [comment]
I keep public reference solutions for all five projects in GitHub if you know where to look, but I wouldn't want them to be listed as branches. I would prefer that people file issues when stuck so that I find out what content needs to be improved.

**Comment by Robbepop** [comment]
I really like the test-driven specification by this PR - it gave me a much better understanding of how the interfaces are meant to work towards the user facing side.
Maybe I will give it a try. :)

**Pull request merged**
